Resources:
  {{ Source | mandatory | resource }}ARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: {{ HostedZone | mandatory | resource}}HostedZone
      Name: {{ Source | mandatory }}
      Type: A
      TTL: '43200'
      ResourceRecords:
      {% for Target in Targets | mandatory %}
        - {{ Target }}
      {% endfor %}