Resources:
  {{ Source | mandatory | resource  }}CNameRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: {{ HostedZone or Domain | mandatory | resource}}HostedZone
      Name: {{ Source }}
      Type: CNAME
      TTL: '43200'
      ResourceRecords:
        {% for Target in Targets | mandatory %}
          - {{ Target }}
        {% endfor %}