Resources:
  {{ Source | resource }}MXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: {{ HostedZone | mandatory | resource }}HostedZone
      Name: {{ Source | mandatory }}
      Type: MX
      TTL: '3600'
      ResourceRecords:
      {% for Target in Targets | mandatory %}
        - {{ Target }}
      {% endfor %}