Resources:
  {{ Source | mandatory | resource}}TXTRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: {{ Source | mandatory }}
      Type: TXT
      HostedZoneId:
        Ref: {{ HostedZone | mandatory | resource}}HostedZone
      TTL: '43200'
      ResourceRecords:
      {% for Target in Targets | mandatory %}
        - '"{{ Target }}"'
      {% endfor %}