Resources:
  {{ module_name | mandatory | resource}}WebBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
  {{ module_name | mandatory | resource}}WebBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref {{ module_name | mandatory | resource}}WebBucket
      PolicyDocument:
        Statement:
        - Action:
          - 's3:GetObject'
          Effect: Allow
          Resource:
          - !Sub 'arn:aws:s3:::${ {{ module_name | mandatory | resource}}WebBucket }/*'
          Principal: '*'
  {{ module_name | mandatory | resource}}RedirectWebBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: {{ Domain }}
          Protocol: https