Resources:
  {{ module_name | mandatory | resource}}Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: {{ Domain }}
      DomainValidationOptions:
        - DomainName: {{ Domain }}
          ValidationDomain: {{ Domain }}
        - DomainName: www.{{ Domain }}
          ValidationDomain: {{ Domain }}
      SubjectAlternativeNames:
        - www.{{ Domain }}
        - '*.{{ Domain }}'