Parameters:
  {{ module_name }}CertificateArn:
    Type: String
    Default: ''

Conditions:
  Has{{ module_name }}CertificateArn:
    !Not [!Equals ['', !Ref {{ module_name }}CertificateArn]]

Resources:
  {{ module_name | mandatory | resource}}BucketDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: 'PriceClass_All'
        HttpVersion: http2
        Origins:
        - DomainName: !Select [2, !Split ['/', !GetAtt '{{ module_name | mandatory | resource}}WebBucket.WebsiteURL']]
          Id: S3WebBucketOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
        Enabled: true
        Aliases:
          - {{ Domain }}
        DefaultCacheBehavior:
          DefaultTTL: 60
          MaxTTL: 300
          TargetOriginId: S3WebBucketOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        ViewerCertificate:
          AcmCertificateArn:
            Fn::If:
              - Has{{ module_name }}CertificateArn
              - !Ref {{ module_name }}CertificateArn
              - !Ref {{ module_name | mandatory | resource}}Certificate
          SslSupportMethod: sni-only

# Redirect Distribution
  {{ module_name | mandatory | resource}}RedirectBucketDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: 'PriceClass_All'
        HttpVersion: http2
        Origins:
        - DomainName: !Select [2, !Split ['/', !GetAtt '{{ module_name | mandatory | resource}}RedirectWebBucket.WebsiteURL']]
          Id: S3WebBucketOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        Enabled: true
        Aliases:
          - www.{{ Domain }}
        DefaultCacheBehavior:
          DefaultTTL: 60
          MaxTTL: 300
          TargetOriginId: S3WebBucketOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        ViewerCertificate:
          AcmCertificateArn:
            Fn::If:
              - Has{{ module_name }}CertificateArn
              - !Ref {{ module_name }}CertificateArn
              - !Ref {{ module_name | mandatory | resource}}Certificate
          SslSupportMethod: sni-only
