Resources:
  {{ domain | mandatory | resource}}WebBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      {% if bucket_name %}
      BucketName: {{ bucket_name }}
      {% endif %}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  {{ domain | mandatory | resource}}WebBucketWebsiteUrl:
    Value: !GetAtt {{ domain | mandatory | resource}}WebBucket.WebsiteURL